---
# tasks file for pg_mediawiki

- name: Установить доп. модули
  ansible.builtin.apt:
    name:
      - python3-psycopg2
      - acl
    state: present

- name: Создать пользователя wikiuser
  become_user: postgres
  ansible.builtin.postgresql_user:
    name: wikiuser
    password: "{{ postgres_wikiuser_password }}"
    state: present
    role_attr_flags: "NOSUPERUSER,NOCREATEDB,NOCREATEROLE"
  when: inventory_hostname == wiki_db_master_vm

- name: Создать базу данных my_wiki
  become_user: postgres
  ansible.builtin.postgresql_db:
    name: my_wiki
    owner: wikiuser
    state: present
  when: inventory_hostname == wiki_db_master_vm
